# Generated by Django 5.2.7 on 2025-10-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En Curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No Asistió')], default='PROGRAMADA', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
